### ISSUE TITLE
impossible branches are not ignored

### ISSUE THREAD

**Issue by skogsbaer** [etylizer/etylizer#36]
With #34, the following test fails:

~~~erlang
-module(test).

-compile(export_all).

-spec foo2 (a) -> 1; (b) -> 2.
foo2(X) ->
    case X of
        a -> 1;
        b -> 2
    end.
~~~

We now investigate what happens when `foo2` is type-checked against `(a) -> 1`. 
For the `case X of ...` part, the following constraints are generated:

~~~
{"case branch":10:1,
      #{A1@0 => $3, X@0 => $4},
      [],
      [{ccase,
        "case":11:5,
        [{cvar, "var X@0":11:10, X@0, $5},
         {csubty, "exhaustiveness check":11:5, $5, a | b}],
        [{"case branch":12:9,
          #{X@0 => $5 /\ a},
          [],
          [{csubty, "int literal":12:14, 1, $6}],
          $5 /\ a},
         {"case branch":13:9,
          #{X@0 => ($5 /\ not(a)) /\ b},
          [],
          [{csubty, "int literal":13:14, 2, $6}],
          ($5 /\ not(a)) /\ b}]},
       {csubty, "result of case":11:5, $6, $1}],
      $0 /\ ({any()} /\ {any()})}
~~~

Here `$5` is a fresh type variable generated for the scrutiny `X`. From the environment, we get that `$4` (the type of `X@0`) must be `a`.

The contraints above can be broken down as follows:

Constraints for the scrutiny X:

~~~
        [{cvar, "var X@0":11:10, X@0, $5},
         {csubty, "exhaustiveness check":11:5, $5, a | b}],
~~~

These two constraints require that the type of `X` is a subtype of `$5` and the exhaustiveness check requires `$5 <= a | b`. By knowing that `X@0` has type `a`, **this should give us the substitution** `<$5 -> a>`.

Constraints for the first clause:

~~~
        {"case branch":12:9,
          #{X@0 => $5 /\ a},
          [],
          [{csubty, "int literal":12:14, 1, $6}],
          $5 /\ a}
~~~

The env `#{X@0 => $5 /\ a}` refines the type of `X`, `$6` is a fresh type variable for the result type. `$5 /\ a` is the guard type of the clause: only if this type is not bottom, the clause can be taken. Under the substitution `<$5 -> a>`, the guard type becomes `a`, which is not bottom.

Constraints for the second clause:

~~~
         {"case branch":13:9,
          #{X@0 => ($5 /\ not(a)) /\ b},
          [],
          [{csubty, "int literal":13:14, 2, $6}],
          ($5 /\ not(a)) /\ b}]}
~~~

This is very similar to the first clause. The guard type is now `($5 /\ not(a)) /\ b`, which can be simplified to `($5 /\ b)`. Under the substitution `<$5 -> a>`, the guard type becomes `a /\ b`, which is bottom. This reflects the fact that the second clause is impossible if the argument type is `a`.

The problem arises during constraint simplification. Here are the relevant parts from the log:

~~~
[DEBUG 2023-09-18 09:41:43.246 constr_simp.erl:101] Checking which branches of case at test.erl:11:5 should be ignored.
Env: {A1@0 => atom() /\ (mu8 | not(mu8) /\ a) |
         integer() /\ mu8 |
         tuple() /\ (mu8 /\ tuple()) |
         fun() /\ (mu8 /\ fun()),
 X@0 => atom() /\ (mu7 | not(mu7) /\ a) |
        integer() /\ mu7 |
        tuple() /\ (mu7 /\ tuple()) |
        fun() /\ (mu7 /\ fun())}
Fixed tyvars: [mu7,mu8]
Constraints for scrutiny:
{[{csubty, "exhaustiveness check":11:5, $5, a | b},
  {csubty,
   "var X@0":11:10,
   atom() /\ (mu7 | not(mu7) /\ a) |
   integer() /\ mu7 |
   tuple() /\ (mu7 /\ tuple()) |
   fun() /\ (mu7 /\ fun()),
   $5}]}
[DEBUG 2023-09-18 09:41:43.246 constr_simp.erl:111] Unique substitution:
{$5 => atom() /\ (mu15 /\ (a | b) | not(mu15) /\ a),
 mu7 => atom() /\ (mu14 /\ (mu15 /\ (a | b) | not(mu15) /\ a))}
~~~

We see that `X@0` does not get the type `a` but a much more complicated type:

~~~
        atom() /\ (mu7 | not(mu7) /\ a) |
        integer() /\ mu7 |
        tuple() /\ (mu7 /\ tuple()) |
        fun() /\ (mu7 /\ fun())
~~~

We can slightly simplify this type

~~~
        atom() /\ mu7 | 
        not(mu7) /\ a) |
        integer() /\ mu7 |
        tuple() /\ mu7 |
        fun() /\ mu7
~~~

But still, it's not the same as `a` (what we would expect). Hence, we get the following substitution:

~~~
<$5 -> mu15 /\ (a | b) | not(mu15) /\ a>
~~~

But under this substitution, the type `$5 /\ b` is not bottom, so the second branch ist not ignored.

**Comment by skogsbaer** [comment]
@albsch This is my analysis of the `foo2` problem. Where do these mu types come from, especially mu7? Somehow the information that X must have type `a` is lost.

**Comment by albsch** [comment]
This is likely the reason of the bug. The tracking of fixed variables between the two different data structures is not properly tested. Let me check.

**Comment by albsch** [comment]
I fixed the bug, fixed variables were not processed correctly. But, looking at the tally input again:

```erlang
{[{csubty,
   "var X@0":7:10,
   atom() /\ (mu7 | not(mu7) /\ a) |
   integer() /\ mu7 |
   tuple() /\ (mu7 /\ tuple()) |
   fun() /\ (mu7 /\ fun()),
   $5},
  {csubty, "exhaustiveness check":7:5, $5, a | b}]}
```

This simplifies to the constraint `mu7 U a <= $5 <= a | b`. 
These two constraints cannot be satisfied by tally, since `mu7` is fixed:

```
debug tallying (['mu7] [('mu7 | `a, 'alpha) ('alpha, `a | `b)]);;
Result:[]
```

Essentially, because:

```
# debug subtype (('mu7 | `a) (`a | `b));;
[DEBUG:subtype]
`a | 'mu7 <= `b | `a : false
```

And therefore the `foo2` test case still fails with a type error.

**Comment by skogsbaer** [comment]
Once this bug is fixed, we should also add support for detecting branches that are redundant even if the type spec of the function is an intersection.

Currently, the check for redudant branches works only for functions that do not have an intersection type.

**Comment by skogsbaer** [comment]
Fixed in #87

**Comment by albsch** [comment]
Just for documentation, I got a slightly different result applying the constraint generation from the paper. It doesn't solve the issue though, continuing to investigate.

When applying this rule

![image](https://github.com/etylizer/etylizer/assets/38429047/85e5a78a-cc15-4e99-976a-c851b448a5c7)

I get the following result:

```math
\frac{
\begin{gathered}
\alpha,\beta \text{ fresh} 
\\
X : \alpha \Rightarrow \lbrace X \leq \alpha \rbrace
\\
C' = \lbrace X \leq \alpha \rbrace \cup C_1 \cup C_1' \cup C_2 \cup C_2' \cup \{\alpha \leq \lceil pg_1 \rceil_X \vee \lceil pg_2 \rceil_X \}
\\
t_1 = \alpha \wedge \lceil pg_1 \rceil_X
\\
t_2 = (\alpha \backslash \lfloor pg_1 \rfloor_X) \wedge \lceil pg_2 \rceil_X
\\
t_1 \mathbin{/\mkern-6mu/} [\negthinspace[ X ]\negthinspace] \Rightarrow \langle C_1; \Gamma_2 \rangle 
\\
t_2 \mathbin{/\mkern-6mu/} [\negthinspace[ X ]\negthinspace] \Rightarrow \langle C_2; \Gamma_2 \rangle 
\\
t_1 \mathbin{/\mkern-6mu/} pg_1 \Rightarrow \langle C_1'; \Gamma_1' \rangle 
\\
t_2 \mathbin{/\mkern-6mu/} pg_2 \Rightarrow \langle C_2'; \Gamma_2' \rangle 
\\
\Gamma_1'' = \Gamma_2 \wedge\negthinspace\negthinspace\negthinspace\negthinspace\wedge \; \Gamma_2'
\\
\Gamma_1'' = \Gamma_2 \wedge\negthinspace\negthinspace\negthinspace\negthinspace\wedge \; \Gamma_2'
\\
e_1 : \beta \Rightarrow C_1''
\\
e_2 : \beta \Rightarrow C_2''
\end{gathered}
}{
\begin{gathered}
\text{case } X \text{ of } a \rightarrow 1 \; b \rightarrow 2 : a
\Rightarrow 
\\
\lbrace \text{case } C' \text{ of } \lparen \Gamma_1'' \text{ in } C_1'' \text{ when } t_1 \quad \Gamma_2'' \text{ in } C_2'' \text{ when } t_2 \rparen, \beta \leq a \rbrace
\end{gathered}
}
```

With 

```math
\begin{gathered} t_1 = \alpha \wedge \lceil pg_1 \rceil_X \\ t_1 = \alpha \wedge \lceil a \text{ when true} \rceil_X \\ t_1 = \alpha \wedge a \\ t_2 = \alpha \backslash a \wedge b \\ \alpha \wedge a \mathbin{/\mkern-6mu/} [\negthinspace[ X ]\negthinspace] \Rightarrow \langle C_1; \Gamma_1 \rangle  \\ \alpha \wedge a \mathbin{/\mkern-6mu/} X \Rightarrow \langle \emptyset; \lbrace X : \alpha \wedge a \rbrace \rangle \\ \alpha \backslash a \wedge b \mathbin{/\mkern-6mu/} [\negthinspace[ X ]\negthinspace] \Rightarrow \langle C_2; \Gamma_2 \rangle  \\ \alpha \backslash a \wedge b \mathbin{/\mkern-6mu/} X \Rightarrow \langle \emptyset; \lbrace X : \alpha \backslash a \wedge b \rbrace \rangle  \\ \alpha \wedge a \mathbin{/\mkern-6mu/} a \text{ when true} \Rightarrow \langle C_1'; \Gamma_1' \rangle  \\ \alpha \wedge a \mathbin{/\mkern-6mu/} a \text{ when true} \Rightarrow \langle \emptyset; \lbrace \rbrace \rangle  \\ \alpha \backslash a \wedge b \mathbin{/\mkern-6mu/} b \text{ when true} \Rightarrow \langle C_2'; \Gamma_2' \rangle  \\ \alpha \backslash a \wedge b \mathbin{/\mkern-6mu/} b \text{ when true} \Rightarrow \langle \emptyset; \lbrace \rbrace \rangle  \end{gathered}
```

Further simplified:

![image](https://github.com/etylizer/etylizer/assets/38429047/8d753e32-50be-4ecc-aa6e-c44a0aeddbfa)

This means, in the notation from the paper, the result is different from your result:

```
def X:a in {
  alpha_1 <= 1,  % constraint for result type
  case {X <= alpha_2, alpha_2 <= a | b} of
    X: alpha_2 /\ a in {1 <= alpha_1} when alpha_2 /\ a
    X: (alpha_2 \ a) /\ b in {2 <= alpha_1} when (alpha_2 \ a) /\ b
}
```
That's likely a typo on your side, the second branch is not yet important.

What's more important is that simplification results in a different set of constraints given to tally:

* We have `X: alpha_2 /\ a` in the first branch
* The scrutiny is simplified to `{alpha_2 /\ a <= alpha_2, alpha_2 <= a | b}`
* Tally (both CDuce and ours) returns this solution: 

```
# debug tallying ([] [] [('alpha & `a, 'alpha) ('alpha, `a | `b)]);;
Result:[{'alpha:=(`b | `a) & 'alphaalpha}]
Cleaned result:[{'alpha:=Empty}]

# debug tallying ([] [] [(`a, 'alpha) ('alpha, `a | `b)]);;
Result:[{'alpha:=`a | (`b | `a) & 'alphaalpha}]
Cleaned result:[{'alpha:=`a}]
```

**Comment by skogsbaer** [comment]
Fixed in PR #98, see the explanation in the PR.

**Comment by skogsbaer** [comment]
Here are a collection of examples. (Please edit this comment if you have more examples.)

~~~erlang
-spec foo2 (a) -> 1; (b) -> 2.
foo2(X) ->
    case X of
        a -> 1;
        b -> 2
    end.
~~~

~~~erlang
-spec f({a, integer()}) -> 1; ({b, integer()}) -> 2.
f(X) ->
    case X of
        {a, _} -> 1;
        {b, _} -> 2
    end.
~~~

~~~erlang
-spec f(a) -> 1; (b) -> 2.
f(X) ->
    case {X, 5}  of
        {a, _} -> 1;
        {b, _} -> 2
    end.
~~~

~~~erlang
-spec g(a) -> c; (b) -> d.
g(a) -> c;
g(b) -> d.

-spec f(a) -> 1; (b) -> 2.
f(X) ->
    case g(X) of
        c -> 1;
        d -> 2
    end.
~~~

~~~erlang
-spec foo4
    (integer()) -> integer();
    (1) -> 2.
foo4(X) ->
    case X of
        1 -> 2;
        _ -> X
    end.
~~~

**Comment by skogsbaer** [comment]
PR #98 does not work for example f4 because equivalence does not propagate through function types.

I'm working on a better solution.

**Comment by skogsbaer** [comment]
Now really fixed in #100

**Comment by skogsbaer** [comment]
#100 fixes all examples from https://github.com/etylizer/etylizer/issues/36#issuecomment-2176342440

But here are some more that fail:

```erlang
-spec fun_local_03() -> integer().
fun_local_03() ->
    F = fun
            Add(0) -> 0;
            Add(X) -> X + Add(X + 1)
        end,
    F(3).
```

```erlang
-spec fun_local_07(1) -> a; (2) -> b.
fun_local_07(X) ->
    F = fun(Y) ->
            case Y of
                1 -> a;
                2 -> b
            end
        end,
    F(X).
```

```erlang
-spec fun_local_07_fail(1) -> a; (2) -> b.
fun_local_07_fail(X) ->
    F = fun(Y) ->
            case Y of
                1 -> c; % result c has wrong type (must be a)
                2 -> b
            end
        end,
    F(X).
```

I think I know how to fix them. Let's explain.,

Currently, constraint simplification marks branches of case expressions as impossible if a certain constraint set is satisfiable. (If the constraint set is satisfiable, then the scrutiny of the case has type that can never match the pattern of the branch). But with local functions, this does not work. Consider a variant of `fun_local_03`:

```erlang
-spec fun_local_03() -> integer().
fun_local_03() ->
    F = fun Add(Y) ->
             case Y of
                0 -> 0
                X ->  X + Add(X + 1)
        end,
    F(3).
```

The constraint for checking impossibility of the first branch `0 -> 0` is essentially $Y <= \neg 0$. But if we do the check "is $Y <= \neg 0$ satisifiable" while simplifying the constraints for the body of `Add`, then the type of $Y$ is some type variable $\alpha$ and so the constraint is satisifiable. That's why PR #100 currently outputs the error "this branch never matches" for branch `0 -> 0`.

For detecting impossible branches, the solution is then to first generate and simplify the constraints for the whole function, without checking the impossibility constraint sets for satisfiability. Assume the constraint set for the whole function is $D$, and $D_i$ are the impossibility constraint sets for the branches of the case expressions. If $D$ is satisfiable, the function is type correct. If $D \cup D_i$ is satisfiable, then then branch associated with $D_i$ is impossible. So for the function to type check, $D$ must be satisfiable and $D \cup D_i$ must not be satisfiable for all $D_i$.

Things get more complicated if intersection types are involved. With intersection types, we type check the function against each type of the intersection. It now might happen that a branch of a case is impossible for one type of the intersection but relevant for some other. Consider

```erlang
-spec fun_local_07(1) -> a; (2) -> b.
fun_local_07(X) ->
    F = fun(Y) ->
            case Y of
                1 -> a;
                2 -> b
            end
        end,
    F(X).
```

The branch `2 -> b` is impossible when checking against type `(1) -> a` but relevant for `(2) -> b`.

Thus, we do not mark impossible branches as erroneous, but we ignore the constraints resulting from the body of the branch. (We ignore the possibility that a branch is impossible for all types if the intersection. This would indeed be a type error.) Assume that for some branch of a case $D_i$ is the impossibility constraint set and $D_i'$ is the constraint set resulting from the body. For the branch to be type correct, $D_i \lor D_i'$ must be satisfiable: either the branch is impossible ($D_i$ is satisifiable) or it is not, so $D_i'$ must be satisifiable.

For `fun_local_07`, we would essentially generate the following constraints. Note that constraints now also involve disjunctions! ($\alpha$ is the type for the parameter of `F`, $\beta$ is the result.)

```math
1 \leq \alpha \land \beta \leq a \land ((\alpha \leq \neg 1) \lor (a \leq \beta)) \land ((\alpha \leq 1|\neg 2) \lor (b \leq \beta))
```

Note that $\land$ and $\lor$ denote logical connectives, not type operators. The union type operator is written $|$, the negtation type operator $\neg$.

In the constraint above, $(\alpha \leq \neg 1) \lor (a \leq \beta)$ is the constraint for the first branch and $(\alpha \leq 1|\neg 2) \lor (b \leq \beta)$ the constraint for the second.

For checking satisfiability of the whole constraint set, we convert it to DNF and use tally to check if at least one of the operands is satisfiable. (For the constraint above, we are at a disjunction with four operands, and tally tells us that one of the operands is satisfiable, so the function is type correct as expected.)

The following function is a variant of `fun_local_07` that should fail to type check:

```erlang
-spec fun_local_07_fail(1) -> a; (2) -> b.
fun_local_07_fail(X) ->
    F = fun(Y) ->
            case Y of
                1 -> c; % result c has wrong type (must be a)
                2 -> b
            end
        end,
    F(X).
```

The constraint for this function are

```math
1 \leq \alpha \land \beta \leq a \land ((\alpha \leq \neg 1) \lor (c \leq \beta)) \land ((\alpha \leq 1|\neg 2) \lor (b \leq \beta))
```

and indeed this constraint is not satisfiable.

The bad news is that, for a single function, tally now has to check potentially many conjunctions of subtyping constraints for satisfiability. The good news is that only functions with an intersection type and that define local functions require this advanced machinery.
